---
name: "TubeArchivistMetadataKids"
guid: "074F9B47-3587-4A92-8D2F-036E5D52F12B"
imageUrl: https://raw.githubusercontent.com/tubearchivist/tubearchivist-jf-plugin/master/images/logo.png
version: "1.3.7.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Metadata for your TubeArchivist Kids library on Jellyfin"
description: >
  TubeArchivistMetadataKids is a plugin that automatically manages
  metadata for videos downloaded with TubeArchivist from YouTube.
category: "Metadata"
owner: "DarkFighterLuke"
artifacts:
- "Jellyfin.Plugin.TubeArchivistMetadataKids.dll"
changelog: >
  Fix JF->TA Sync
